# optional parameter spring.throttling.lru-cache-capacity, default value is 10000
spring:
  throttling:
    lru-cache-capacity: 100
    controller-request-per-minute: 3

  application:
    name: example

logging:
  level:
    com.weddini.throttling: DEBUG
